variables:
  APP_NAME: the-insecure-proxy

stages:
  - test
  - build
  - package-build
  - package-test
  - publish
  - acceptance
  - production
  - deploy

include:
  - component: $CI_SERVER_FQDN/to-be-continuous/helm/gitlab-ci-helm@9
    inputs:
      chart-dir: ./chart
  - component: $CI_SERVER_FQDN/to-be-continuous/docker/gitlab-ci-docker@8
    inputs:
      build-tool: buildah
      build-args: "--platform linux/amd64 --platform linux/arm64"
      snapshot-image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
      release-image: "${CI_REGISTRY_IMAGE}:latest"
      prod-publish-strategy: auto
      hadolint-disabled: true

docker-buildah-build:
  tags:
    - buildah

build:
  stage: build
  image: rust:1.97
  script:
    - cargo fetch
    - cargo test --all-targets
    - cargo build --release
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
  artifacts:
    paths:
      - target/release/the-insecure-proxy
  cache:
    paths:
      - target
      - .cargo

# todo: replace with argocd
deploy:
  stage: deploy
  image:
    name: alpine/helm:4.2.3
    entrypoint: [ "" ]
  script:
    - >-
      helm upgrade "${APP_NAME}" ./chart --install --atomic \
           --values=./chart/values.yaml \
           --namespace "${KUBE_NAMESPACE}" \
           --set "applicationName=${APP_NAME}" \
           --set "image=${CI_REGISTRY_IMAGE}:latest" \
           --set "imagePullSecret=image-pull-secret-${APP_NAME}" \
           --set "priorityClassName=fun-stuff"
  needs:
    - helm-lint
    - docker-publish
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always
