---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      {{ if .Values.priorityClassName }}
      priorityClassName: fun-stuff
      {{ end }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Values.applicationName }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: PORT
              value: "5000"
            - name: BIND_ADDRESS
              value: "0.0.0.0"
          ports:
            - name: http
              containerPort: 5000
---
