---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.applicationName }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.externalPort }}
      targetPort: 5000
